### ISSUE TITLE
import multiresolutionimageinterface ERROR

### ISSUE THREAD

**Issue by yingdiLee** [computationalpathologygroup/ASAP#146]
when I import  multiresolutionimageinterface in python, an error occurs:
Traceback (most recent call last):
  File "/home/zyd/PycharmProjects/WSIRecognize/access_data.py", line 11, in <module>
    import multiresolutionimageinterface
  File "/opt/ASAP/bin/multiresolutionimageinterface.py", line 28, in <module>
    _multiresolutionimageinterface = swig_import_helper()
  File "/opt/ASAP/bin/multiresolutionimageinterface.py", line 24, in swig_import_helper
    _mod = imp.load_module('_multiresolutionimageinterface', fp, pathname, description)
  File "/home/zyd/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/zyd/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

how to solve it?

**Comment by GeertLitjens** [comment]
You are using Python 3.7 whereas ASAP is compile against 3.6, they are not binary compatible

**Comment by superxudou** [comment]
Must GCC be version 5.0 or higher? I also get segment default. My GCC is 4.8
